#include "compiler_driver.hpp"
#include <cstdlib>
#include <filesystem>
#include <sstream>
#include <stdexcept>

namespace {

std::string findSourceRoot(const std::string& inputPath) {
    std::filesystem::path p = std::filesystem::absolute(inputPath).parent_path();
    for (;;) {
        if (std::filesystem::exists(p / "src" / "runtime" / "lanner_runtime.c")) return p.string();
        const auto parent = p.parent_path();
        if (parent == p) break;
        p = parent;
    }
    if (const char* env = std::getenv("LANNER_ROOT")) return env;
    return std::filesystem::current_path().string();
}

std::string safeName(std::string value) {
    if (value.empty()) return "LannerGame";
    for (char& c : value) {
        const bool ok = (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
                        (c >= '0' && c <= '9') || c == '_' || c == '-';
        if (!ok) c = '_';
    }
    return value;
}

std::string cmakeName(std::string value) {
    for (char& c : value) if (c == '-') c = '_';
    return value.empty() ? "LannerGame" : value;
}

} // namespace

int CompilerDriver::generateGameProject(const CompilerOptions& options, const std::string& source) {
    if (options.gameBackend != "sdl2") {
        throw std::runtime_error("unsupported game backend '" + options.gameBackend + "' (currently supported: sdl2)");
    }

    const std::filesystem::path dir(options.gameProjectPath);
    const std::filesystem::path root(findSourceRoot(options.inputPath));
    const std::string appName = safeName(options.gameAppName);
    const std::string cmakeTarget = cmakeName(appName);
    std::error_code ec;
    std::filesystem::create_directories(dir / "src", ec);
    if (ec) throw std::runtime_error("cannot create game project directory");
    std::filesystem::create_directories(dir / "assets", ec);
    if (ec) throw std::runtime_error("cannot create game assets directory");

    const auto write = [&](const std::filesystem::path& relative, const std::string& content) {
        if (!writeTextFile((dir / relative).string(), content)) {
            throw std::runtime_error("cannot write game project file '" + (dir / relative).string() + "'");
        }
    };

    write("src/main.lan", source);
    write("src/lanner_runtime.c", readFile((root / "src/runtime/lanner_runtime.c").string()));
    write("assets/.gitkeep", "");

    std::ostringstream cmake;
    cmake << "cmake_minimum_required(VERSION 3.20)\n"
          << "project(" << cmakeTarget << " LANGUAGES C)\n\n"
          << "set(CMAKE_C_STANDARD 11)\n"
          << "set(CMAKE_C_STANDARD_REQUIRED ON)\n"
          << "set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)\n\n"
          << "if(NOT DEFINED LANNERC_EXECUTABLE)\n"
          << "  find_program(LANNERC_EXECUTABLE lanner REQUIRED)\n"
          << "endif()\n\n"
          << "set(LANNER_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/src/main.lan)\n"
          << "set(LANNER_OBJECT ${CMAKE_CURRENT_BINARY_DIR}/lanner_game.o)\n"
          << "add_custom_command(OUTPUT ${LANNER_OBJECT}\n"
          << "  COMMAND ${LANNERC_EXECUTABLE} ${LANNER_SOURCE} --backend=llvm --no-runtime --emit-object -O3 -o ${LANNER_OBJECT}\n"
          << "  DEPENDS ${LANNER_SOURCE} ${LANNERC_EXECUTABLE}\n"
          << "  VERBATIM)\n\n"
          << "add_executable(" << cmakeTarget << " ${LANNER_OBJECT} src/lanner_runtime.c)\n"
          << "set_target_properties(" << cmakeTarget << " PROPERTIES OUTPUT_NAME \"" << appName << "\")\n"
          << "if(WIN32)\n"
          << "  target_link_libraries(" << cmakeTarget << " PRIVATE ws2_32)\n"
          << "else()\n"
          << "  target_link_libraries(" << cmakeTarget << " PRIVATE dl m pthread)\n"
          << "endif()\n\n"
          << "add_custom_target(run COMMAND $<TARGET_FILE:" << cmakeTarget << "> DEPENDS " << cmakeTarget
          << " WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})\n";
    write("CMakeLists.txt", cmake.str());

    std::ostringstream readme;
    readme << "# " << appName << "\n\n"
           << "Native Lanner game project generated by `lanner --game-project`.\n\n"
           << "## Build\n\n"
           << "```sh\n"
           << "cmake -S . -B build -DLANNERC_EXECUTABLE=/path/to/lanner\n"
           << "cmake --build build -j\n"
           << "```\n\n"
           << "Run with `cmake --build build --target run`.\n\n"
           << "## Runtime dependency\n\n"
           << "Lanner's game layer dynamically loads SDL2. The generated project does not require SDL2 development headers at compile time, but the SDL2 runtime must be available. Typical runtime names are `libSDL2-2.0.so.0` on Linux, `libSDL2.dylib` on macOS, and `SDL2.dll` on Windows.\n\n"
           << "## API layers\n\n"
           << "`Game` provides the SDL2 window, event/input, 2D renderer, texture, audio and frame-clock layer. `Graphics` provides OpenGL wrappers and a generic unsafe procedure loader for Vulkan, Metal and Direct3D.\n\n"
           << "## Assets\n\n"
           << "Place game assets under `assets/`. Asset importers and build tools can be written in Lanner or invoked through the process APIs.\n";
    write("README.md", readme.str());
    write(".gitignore", "build/\n*.o\n*.obj\n*.exe\n");
#if defined(_WIN32)
    write("build.ps1", "cmake -S . -B build -DLANNERC_EXECUTABLE=lanner\ncmake --build build --config Release\n");
#else
    write("build.sh", "#!/bin/sh\nset -eu\ncmake -S . -B build -DLANNERC_EXECUTABLE=\"${LANNERC_EXECUTABLE:-lanner}\"\ncmake --build build -j\n");
    std::error_code chmodEc;
    std::filesystem::permissions(dir / "build.sh",
        std::filesystem::perms::owner_read | std::filesystem::perms::owner_write | std::filesystem::perms::owner_exec |
        std::filesystem::perms::group_read | std::filesystem::perms::group_exec |
        std::filesystem::perms::others_read | std::filesystem::perms::others_exec,
        std::filesystem::perm_options::add, chmodEc);
#endif
    return 0;
}
